<?php

declare(strict_types=1);

namespace Heisenberg\Services;

use Heisenberg\Models\Post;
use Heisenberg\Support\EmailBatchExportResult;
use Heisenberg\Support\EmailBatchTranslationMissingException;
use Heisenberg\Support\EmailVariableContext;
use Heisenberg\Support\EmailVariableResolutionException;
use Heisenberg\Support\LocaleConfig;
use InvalidArgumentException;
use Illuminate\Support\Str;
use Symfony\Component\Mime\Address;
use Symfony\Component\Mime\Email as SymfonyEmail;
use Symfony\Component\Mime\Exception\LogicException as MimeLogicException;
use Symfony\Component\Mime\Part\DataPart;
use Symfony\Component\Mime\Part\File as MimeFile;
use Throwable;
use ZipArchive;

/**
 * Admin batch file factory (.hermes/plans/2026-08-25_190059-email-template-variables.md,
 * Task 6): host-supplied recipient value maps × requested locales → one
 * zip on disk. Sending those files is the host's mailer, never this
 * package. The exporter does NOT call Mail::send, does NOT touch SMTP,
 * does NOT enumerate RoleGate members as recipients, and does NOT
 * persist any of the values it consumes.
 *
 * NON-GOALS (locked product decisions, plan §"Locked product decisions"):
 *  - No SMTP, mailer config, queue worker, or delivery attempt.
 *  - No subscriber / campaign / scheduling tables. N is the literal
 *    `count($recipients)` the admin (or host job) passed in.
 *  - No Eloquent introspection: keys must already be registered,
 *    values are NEVER persisted onto the email post.
 *  - No format other than `eml` and `html`; no locale outside the
 *    configured set; no recipient id that isn't filename-safe and
 *    unique within a batch.
 *  - No partial zip on a per-recipient or per-locale failure: the
 *    whole batch is rolled back, so an admin never ships a truncated
 *    campaign.
 *
 * ZIP LAYOUT (the only layout the contract produces):
 *
 *   {slug}/{locale}/{id}.{html|eml}
 *
 * `{slug}` is the email post's own slug (`Post::$slug`, generated by
 * the model's own slug hook). `{locale}` and `{id}` come straight from
 * the validated input. Files are added in the same order they are
 * produced: locale-major, recipient-minor — a predictable shape that
 * matches what the test suite asserts.
 *
 * HTML batch uses the SAME `preview: true` render the slug GET serves
 * (real, publicly-fetchable image URLs, no `cid:` scheme) — but every
 * `<img src="/...">` is then absolutized with the app's own base URL,
 * exactly like {@see \Heisenberg\Http\Controllers\EmailPreviewController::exportHtml()}.
 * EML batch uses the REAL cid-embedded render and a Symfony Mime
 * message built per file; `From` is set ONLY when
 * `config('mail.from.address')` is non-empty — when it isn't,
 * Symfony's `Message::getPreparedHeaders()` throws a LogicException and
 * the exporter surfaces a controlled, non-Symfony exception so a host
 * sees "configure mail.from.address" rather than a stack trace.
 *
 * CLEANUP: the temporary zip is written into `storage_path('app')` with
 * a per-batch unique name (`email-batch-{uuid}.zip`). On ANY per-row
 * or per-batch failure (including the no-Symfony-From case for EML),
 * the zip is deleted from disk before the exception propagates — an
 * admin never sees a half-zipped file on disk to download by accident.
 *
 * The constructor takes the renderer directly (already a singleton in
 * {@see \Heisenberg\HeisenbergServiceProvider::registerEngine()}). No
 * SMTP client, no mailer facade, no Carbon — see
 * {@see \Heisenberg\Http\Controllers\EmailBatchExportController} for the
 * HTTP-layer wrapping.
 */
class EmailBatchExporter
{
    public function __construct(
        private EmailRenderer $renderer,
        private EmailVariableRegistry $variables,
        private TranslationStatusService $translationStatus,
    ) {
    }

    /**
     * Cap on the recipient count a single batch may carry. Mirrors
     * `config('heisenberg.email.batch_max_recipients')` (default 100); the
     * config key is host-overridable, so this reads it at call time rather
     * than caching once at construction.
     */
    private function maxRecipients(): int
    {
        return (int) config('heisenberg.email.batch_max_recipients', 100);
    }

    /**
     * Generate the per-recipient zip. Validates everything first (format,
     * locales, recipient count, id shape, id uniqueness, value map shape,
     * value keys registered), then renders N×locales files into a fresh
     * zip, deleting the zip on any per-row failure so the on-disk state is
     * always all-or-nothing. Returns the result DTO.
     *
     * @param array{
     *     format?: 'eml'|'html',
     *     locales?: list<string>,
     *     recipients: list<array{id: string, values: array<string, mixed>}>,
     * } $options
     *
     * @throws InvalidArgumentException on any structural validation failure
     * @throws EmailVariableResolutionException aggregated, on any resolution failure
     *         (no zip on disk after this throws — see $path handling below)
     */
    public function export(Post $email, array $options): EmailBatchExportResult
    {
        $format = $this->validateFormat($options);
        $locales = $this->validateLocales($options);
        $recipients = $this->validateRecipients($options);
        $this->validateTranslationsPresent($email, $locales);

        $registered = $this->registeredVariableKeys();
        foreach ($recipients as $i => $recipient) {
            foreach ($recipient['values'] as $key => $value) {
                if (! is_string($key)) {
                    throw new InvalidArgumentException(sprintf(
                        'Recipient #%d has a non-string values key; expected a flat dotted-key map.',
                        $i + 1,
                    ));
                }
                if (! isset($registered[$key])) {
                    throw new InvalidArgumentException(sprintf(
                        'Recipient #%d value for "%s" references an unregistered variable; register the variable first via EmailVariableRegistry.',
                        $i + 1,
                        $key,
                    ));
                }
            }
        }

        $files = [];
        $failures = [];
        $slug = $this->slugFor($email);

        foreach ($locales as $locale) {
            foreach ($recipients as $recipient) {
                $context = EmailVariableContext::runtime($recipient['values']);
                try {
                    if ($format === 'html') {
                        $result = $this->renderer->render($email, $locale, preview: true, variables: $context);
                        $bytes = $this->wrapHtmlForBatch($result->html);
                    } else {
                        $result = $this->renderer->render($email, $locale, variables: $context);
                        $bytes = $this->buildEmlForBatch($result->subject, $result->text, $result->html, $result->embeds);
                    }
                } catch (EmailVariableResolutionException $e) {
                    foreach ($e->getFailures() as $failure) {
                        $failures[] = [
                            'key' => $recipient['id'] . '/' . $locale . '/' . $failure['key'],
                            'reason' => $failure['reason'],
                        ];
                    }
                    continue;
                }

                $entry = sprintf('%s/%s/%s.%s', $slug, $locale, $recipient['id'], $format);
                $files[$entry] = $bytes;
            }
        }

        if ($failures !== []) {
            throw new EmailVariableResolutionException($failures);
        }

        if (! class_exists(ZipArchive::class)) {
            throw new \RuntimeException('Batch export requires the PHP ZipArchive extension.');
        }

        $path = $this->allocatePath();
        $zip = new ZipArchive();
        if ($zip->open($path, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
            $this->deleteQuietly($path);
            throw new \RuntimeException('Could not open a temporary batch zip for writing.');
        }

        try {
            foreach ($files as $entry => $bytes) {
                if (! $zip->addFromString($entry, $bytes)) {
                    throw new \RuntimeException(sprintf('Could not add "%s" to the temporary batch zip.', $entry));
                }
            }
            if (! $zip->close()) {
                throw new \RuntimeException('Could not finalize the temporary batch zip.');
            }

            return new EmailBatchExportResult(
                path: $path,
                fileCount: count($files),
                recipientCount: count($recipients),
                locales: $locales,
            );
        } catch (Throwable $e) {
            if ($zip->filename !== false) {
                $zip->close();
            }
            $this->deleteQuietly($path);
            throw $e;
        }
    }

    /**
     * Reject anything other than `eml` / `html`. A typo (`pd`, `Pdf`) is
     * a host-side mistake the admin MUST see, never silently default.
     */
    private function validateFormat(array $options): string
    {
        $format = $options['format'] ?? 'html';
        if (! is_string($format) || ($format !== 'eml' && $format !== 'html')) {
            throw new InvalidArgumentException(sprintf(
                'Batch format must be "html" or "eml"; got %s.',
                is_string($format) ? '"' . $format . '"' : gettype($format),
            ));
        }

        return $format;
    }

    /**
     * Default to every configured locale; reject anything outside the
     * installed set (so a typo cannot fall back to en). An empty list
     * triggers the default; a non-empty list is validated as-is.
     *
     * @return list<string>
     */
    private function validateLocales(array $options): array
    {
        $configured = LocaleConfig::locales();
        $locales = $options['locales'] ?? $configured;

        if (! is_array($locales)) {
            throw new InvalidArgumentException('Batch locales must be a list of strings; null/empty means use every configured locale.');
        }

        $resolved = [];
        $seen = [];
        foreach ($locales as $locale) {
            if (! is_string($locale) || $locale === '') {
                throw new InvalidArgumentException('Batch locales must be a list of non-empty strings.');
            }
            if (! LocaleConfig::isValid($locale)) {
                throw new InvalidArgumentException(sprintf(
                    'Batch locale "%s" is not in config("heisenberg.locales") (%s).',
                    $locale,
                    implode(', ', $configured),
                ));
            }
            if (isset($seen[$locale])) {
                throw new InvalidArgumentException(sprintf(
                    'Batch locales contain a duplicate "%s"; each locale appears exactly once per batch.',
                    $locale,
                ));
            }
            $seen[$locale] = true;
            $resolved[] = $locale;
        }

        return $resolved === [] ? $configured : $resolved;
    }

    /**
     * Validate recipient list shape. Empty → 422-ish error. Over cap →
     * same. Each row is `{id: string, values: array<string, mixed>}`,
     * the id is filename-safe and unique across the batch.
     *
     * @return list<array{id: string, values: array<string, mixed>}>
     */
    private function validateRecipients(array $options): array
    {
        if (! array_key_exists('recipients', $options) || ! is_array($options['recipients'])) {
            throw new InvalidArgumentException('Batch recipients must be a list of {id, values} entries.');
        }
        $recipients = $options['recipients'];
        if ($recipients === []) {
            throw new InvalidArgumentException('Batch recipients must not be empty; pass at least one {id, values} entry.');
        }

        $max = $this->maxRecipients();
        if (count($recipients) > $max) {
            throw new InvalidArgumentException(sprintf(
                'Batch recipients exceed the cap of %d (got %d); raise config("heisenberg.email.batch_max_recipients") if a larger batch is intentional.',
                $max,
                count($recipients),
            ));
        }

        $seen = [];
        foreach ($recipients as $i => $recipient) {
            if (! is_array($recipient) || ! isset($recipient['id'], $recipient['values']) || ! is_array($recipient['values'])) {
                throw new InvalidArgumentException(sprintf(
                    'Recipient #%d must be {id: string, values: object}.',
                    $i + 1,
                ));
            }
            $id = $recipient['id'];
            if (! is_string($id) || $id === '' || ! preg_match('/^[A-Za-z0-9][A-Za-z0-9._-]*$/', $id)) {
                throw new InvalidArgumentException(sprintf(
                    'Recipient #%d id "%s" must be a non-empty filename-safe slug ([A-Za-z0-9._-]).',
                    $i + 1,
                    is_string($id) ? $id : gettype($id),
                ));
            }
            if (isset($seen[$id])) {
                throw new InvalidArgumentException(sprintf(
                    'Recipient id "%s" appears more than once in the batch; each id must be unique per batch.',
                    $id,
                ));
            }
            $seen[$id] = true;
        }

        return array_values($recipients);
    }

    /**
     * Verify the single-row post has complete persisted content for every
     * requested locale. The plan's "persisted translation required per locale,
     * no mislabeled fallback" rule makes a missing translation structural (NOT a
     * per-token resolution failure) and surfaces as
     * {@see EmailBatchTranslationMissingException}.
     *
     * @param list<string> $locales
     */
    private function validateTranslationsPresent(Post $email, array $locales): void
    {
        $statuses = [];
        foreach ($this->translationStatus->statuses($email) as $status) {
            $statuses[(string) $status['locale']] = (bool) $status['complete'];
        }
        $missing = [];
        foreach ($locales as $locale) {
            if (($statuses[$locale] ?? false) !== true) {
                $missing[] = $locale;
            }
        }

        if ($missing !== []) {
            throw new EmailBatchTranslationMissingException(
                $missing,
                trim((string) ($email->locale ?? '')) ?: LocaleConfig::default(),
            );
        }
    }

    /**
     * Pre-collect the set of registered variable keys so a value-map
     * check is O(N+M) instead of O(N×M). The registry is a singleton —
     * this is the same instance a host registered keys on during boot.
     *
     * @return array<string, true>
     */
    private function registeredVariableKeys(): array
    {
        $keys = [];
        foreach ($this->variables->definitions() as $definition) {
            $keys[$definition->key] = true;
        }

        return $keys;
    }

    /**
     * Allocate a unique path inside `storage_path('app')` (the default
     * Laravel app disk root, NOT the public uploads disk — batch zips
     * are private to the admin who requested them, never public). The
     * filename carries a UUID4 prefix so concurrent batches do not
     * collide, and `.zip` so a host can audit file types at a glance.
     */
    private function allocatePath(): string
    {
        $dir = storage_path('app');
        if (! is_dir($dir)) {
            @mkdir($dir, 0775, true);
        }

        $name = 'email-batch-' . bin2hex(random_bytes(8)) . '-' . bin2hex(random_bytes(8)) . '.zip';

        return $dir . DIRECTORY_SEPARATOR . $name;
    }

    /**
     * The email's own slug, used as the top-level directory inside the
     * zip. Falls back to `untitled` to match the model's own slug hook —
     * an unsaved/slugless email row is an authoring mistake we still
     * want to render deterministically rather than crashing.
     */
    private function slugFor(Post $email): string
    {
        $slug = Str::slug(trim((string) ($email->slug ?? '')));

        return $slug !== '' ? $slug : 'untitled';
    }

    /**
     * Same absolutize step the single-document HTML export does —
     * root-relative `/uploads/...` paths get the host's base URL
     * prepended, so an ESP ingesting the raw HTML can resolve every
     * `<img src>` without needing the editor's page context.
     */
    private function wrapHtmlForBatch(string $html): string
    {
        $base = rtrim((string) url('/'), '/');

        return (string) preg_replace_callback(
            '/(<img\b[^>]*\ssrc=\")(\/[^\"]*)(\")/i',
            static fn (array $m): string => $m[1] . $base . $m[2] . $m[3],
            $html,
        );
    }

    /**
     * Build the `.eml` file with the SAME shape Symfony Mime produces
     * for {@see \Heisenberg\Mail\HeisenbergMailable}: subject, plain
     * text, html, every embed re-attached as an inline part keyed to
     * the exact cid the renderer already wrote into the HTML. `From`
     * comes from `mail.from.{address,name}` and is set ONLY when
     * configured — otherwise we throw a controlled
     * `InvalidArgumentException` (caller-friendly, not Symfony's
     * LogicException) so the caller sees "configure mail.from.address".
     *
     * @param list<array{cid: string, path: string, mime: string}> $embeds
     */
    private function buildEmlForBatch(string $subject, string $text, string $html, array $embeds): string
    {
        $fromAddress = trim((string) config('mail.from.address', ''));
        if ($fromAddress === '') {
            throw new InvalidArgumentException(
                'Cannot export .eml: configure mail.from.address (and optionally mail.from.name) before generating a batch.',
            );
        }

        $email = (new SymfonyEmail())
            ->subject($subject)
            ->text($text)
            ->html($html);

        $fromName = trim((string) config('mail.from.name', ''));
        $email->from($fromName !== '' ? new Address($fromAddress, $fromName) : new Address($fromAddress));

        foreach ($embeds as $embed) {
            $part = (new DataPart(new MimeFile($embed['path']), null, $embed['mime']))
                ->asInline()
                ->setContentId($embed['cid']);
            $email->addPart($part);
        }

        try {
            return $email->toString();
        } catch (MimeLogicException) {
            throw new InvalidArgumentException(
                'Cannot export .eml: configure mail.from.address (and optionally mail.from.name) before generating a batch.',
            );
        }
    }

    /**
     * Quietly remove a temp file — used by the all-or-nothing rollback
     * path. A failure here is logged but never re-thrown: the original
     * exception is the one that matters to the admin.
     */
    private function deleteQuietly(string $path): void
    {
        try {
            if (is_file($path)) {
                @unlink($path);
            }
        } catch (\Throwable) {
            // ignored — never mask the original failure
        }
    }
}
